#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.1 effective-5.10 (swiftlang-6.3.1.1.2 clang-2100.0.123.102)
#ifndef CHOTTULINKSDK_SWIFT_H
#define CHOTTULINKSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ChottuLinkSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ChottuLinkSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// A model representing attribution data for the current app install.
/// <h2>Use <code>ChottuLink/getAttributionData()</code> to retrieve cached attribution data.</h2>
SWIFT_CLASS("_TtC13ChottuLinkSDK17CLAttributionData")
@interface CLAttributionData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull attributionType;
@property (nonatomic, readonly, copy) NSString * _Nullable installId;
@property (nonatomic, readonly) BOOL matchFound;
@property (nonatomic, readonly, copy) NSString * _Nullable matchType;
@property (nonatomic, readonly, copy) NSString * _Nullable shortUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable clickedShortUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable destinationUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable destinationWithUtm;
@property (nonatomic, readonly, copy) NSString * _Nullable utmSource;
@property (nonatomic, readonly, copy) NSString * _Nullable utmMedium;
@property (nonatomic, readonly, copy) NSString * _Nullable utmCampaign;
@property (nonatomic, readonly, copy) NSString * _Nullable utmTerm;
@property (nonatomic, readonly, copy) NSString * _Nullable utmContent;
@property (nonatomic, readonly) BOOL isAttributed;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol ChottuLinkDelegate;
/// The configuration structure for setting up the ChottuLink SDK in your app.
/// This structure contains all the settings you need to get started with ChottuLink.
/// Think of it as your SDK’s control center - it lets you set up your API key,
/// enable debugging, and connect to the SDK’s event system.
/// <h2>Quick Start</h2>
/// \code
/// // Basic setup with just your API key
/// let config = CLConfiguration(apiKey: "your-api-key")
///
/// // Full setup with all options
/// let config = CLConfiguration(
/// apiKey: "your-api-key",
/// isDebugEnabled: true,
/// delegate: self
/// )
///
/// \endcode<h2>What You Can Configure</h2>
/// <ul>
///   <li>
///     <code>apiKey</code>: Your unique identifier for the ChottuLink service
///   </li>
///   <li>
///     <code>isDebugEnabled</code>: Toggle for detailed logging during development
///   </li>
///   <li>
///     <code>delegate</code>: Connect to receive SDK events and updates
///   </li>
/// </ul>
/// <h2>Best Practices</h2>
/// <ul>
///   <li>
///     Store your API key securely, preferably in a configuration file or environment variable
///   </li>
///   <li>
///     Only enable debug mode during development
///   </li>
///   <li>
///     Set up your delegate early to catch all SDK events
///   </li>
///   <li>
///     Keep your configuration consistent across app launches
///   </li>
/// </ul>
/// <h2>Common Use Cases</h2>
/// <ol>
///   <li>
///     <em>Basic Integration</em>
///   </li>
/// </ol>
/// \code
/// let config = CLConfiguration(apiKey: "your-api-key")
/// ChottuLink.initialize(config: config)
///
/// \endcode<ol>
///   <li>
///     <em>Development Setup</em>
///   </li>
/// </ol>
/// \code
/// let config = CLConfiguration(
/// apiKey: "your-api-key",
/// isDebugEnabled: true
/// )
/// ChottuLink.initialize(config: config)
///
/// \endcode<ol>
///   <li>
///     <em>Full Integration with Events</em>
///   </li>
/// </ol>
/// \code
/// class MyViewController: UIViewController, ChottuLinkDelegate {
/// override func viewDidLoad() {
/// super.viewDidLoad()
/// let config = CLConfiguration(
/// apiKey: "your-api-key",
/// isDebugEnabled: true,
/// delegate: self
/// )
/// ChottuLink.initialize(config: config)
/// }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC13ChottuLinkSDK15CLConfiguration")
@interface CLConfiguration : NSObject
/// Your unique API key for the ChottuLink service.
/// This key is your passport to the ChottuLink service. It’s used to:
/// <ul>
///   <li>
///     Authenticate your app’s requests
///   </li>
///   <li>
///     Track your app’s usage
///   </li>
///   <li>
///     Access your dashboard data
///   </li>
/// </ul>
/// You can find your API key in the ChottuLink dashboard under Settings > API Keys.
/// <h2>Security Tips</h2>
/// important:
/// This key is required and must be valid
/// note:
/// Keep this key secure - it’s like a password for your app
/// <ul>
///   <li>
///     Never commit your API key to version control
///   </li>
///   <li>
///     Don’t expose it in client-side code
///   </li>
///   <li>
///     Consider using environment variables or a secure configuration system
///   </li>
/// </ul>
@property (nonatomic, copy) NSString * _Nonnull apiKey;
/// Toggle for detailed logging during development.
/// When enabled, you’ll see detailed logs about:
/// <ul>
///   <li>
///     Network requests and responses
///   </li>
///   <li>
///     Link resolution attempts
///   </li>
///   <li>
///     SDK state changes
///   </li>
///   <li>
///     Error details
///   </li>
/// </ul>
/// This is super helpful during development but should be turned off in production.
/// <h2>When to Use</h2>
/// <ul>
///   <li>
///     During development and testing
///   </li>
///   <li>
///     When debugging link issues
///   </li>
///   <li>
///     When implementing new features
///   </li>
/// </ul>
/// <h2>When to Avoid</h2>
/// note:
/// Debug mode can impact performance
/// warning:
/// Don’t enable in production - it might expose sensitive information
/// <ul>
///   <li>
///     In production builds
///   </li>
///   <li>
///     In release candidates
///   </li>
///   <li>
///     When performance is critical
///   </li>
/// </ul>
@property (nonatomic) BOOL isDebugEnabled;
/// Your connection to the SDK’s event system.
/// The delegate is your window into the SDK’s world. It lets you:
/// <ul>
///   <li>
///     Know when links are resolved
///   </li>
///   <li>
///     Handle errors gracefully
///   </li>
///   <li>
///     Track user interactions
///   </li>
///   <li>
///     Monitor SDK performance
///   </li>
/// </ul>
/// <h2>Setting Up Your Delegate</h2>
/// \code
/// class MyViewController: UIViewController, ChottuLinkDelegate {
/// override func viewDidLoad() {
/// super.viewDidLoad()
/// let config = CLConfiguration(
/// apiKey: "your-api-key",
/// delegate: self
/// )
/// ChottuLink.initialize(config: config)
/// }
/// }
///
/// \endcodenote:
/// The delegate is optional but highly recommended
/// important:
/// Set this before initializing the SDK
/// warning:
/// Use a class instance to prevent memory issues
@property (nonatomic, strong) id <ChottuLinkDelegate> _Nullable delegate;
/// Creates a new configuration for the ChottuLink SDK.
/// This is your starting point for setting up the SDK. You can configure everything
/// from basic authentication to detailed debugging in one place.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     apiKey: Your unique API key from the ChottuLink dashboard
///   </li>
///   <li>
///     isDebugEnabled: Whether to show detailed logs (default: false)
///   </li>
///   <li>
///     delegate: Your connection to SDK events (default: nil)
///   </li>
/// </ul>
/// <h2>Examples</h2>
/// \code
/// // Basic setup
/// let config = CLConfiguration(apiKey: "your-api-key")
///
/// // Development setup
/// let devConfig = CLConfiguration(
/// apiKey: "your-api-key",
/// isDebugEnabled: true
/// )
///
/// // Full setup with events
/// let fullConfig = CLConfiguration(
/// apiKey: "your-api-key",
/// isDebugEnabled: true,
/// delegate: self
/// )
///
/// \endcodenote:
/// The API key is the only required parameter
/// important:
/// Set up your delegate early to catch all events
/// warning:
/// Keep debug mode off in production
- (nonnull instancetype)initWithApiKey:(NSString * _Nonnull)apiKey isDebugEnabled:(BOOL)isDebugEnabled delegate:(id <ChottuLinkDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <h2>Conversion / revenue payload for <code>ChottuLink/trackConversion(_:)</code>.</h2>
SWIFT_CLASS("_TtC13ChottuLinkSDK16CLConversionMeta")
@interface CLConversionMeta : NSObject
@property (nonatomic, readonly) double revenue;
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable eventName;
@property (nonatomic, readonly, copy) NSString * _Nullable productId;
@property (nonatomic, readonly, copy) NSString * _Nullable transactionId;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable metadata;
- (nonnull instancetype)initWithRevenue:(double)revenue currency:(NSString * _Nullable)currency eventName:(NSString * _Nullable)eventName productId:(NSString * _Nullable)productId transactionId:(NSString * _Nullable)transactionId metadata:(NSDictionary<NSString *, id> * _Nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// <h2>Customer identity for <code>ChottuLink/identify(_:)</code>.</h2>
SWIFT_CLASS("_TtC13ChottuLinkSDK14CLCustomerMeta")
@interface CLCustomerMeta : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable email;
@property (nonatomic, readonly, copy) NSString * _Nullable phone;
@property (nonatomic, readonly, copy) NSString * _Nullable emailSha256;
@property (nonatomic, readonly, copy) NSString * _Nullable phoneSha256;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nullable)name email:(NSString * _Nullable)email phone:(NSString * _Nullable)phone emailSha256:(NSString * _Nullable)emailSha256 phoneSha256:(NSString * _Nullable)phoneSha256 OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Defines how a dynamic link should behave when opened by a user.
/// This enum lets you control whether your dynamic links should open in a web browser
/// or directly in your app. It’s like choosing the best path for your users to reach
/// their destination.
/// note:
/// The behavior is just a preference - the actual opening method
/// might depend on the user’s device and settings
/// <h2>Available Behaviors</h2>
/// <ul>
///   <li>
///     <code>browser</code>: Opens the link in the device’s default web browser
///   </li>
///   <li>
///     <code>app</code>: Attempts to open the link directly in your app
///   </li>
/// </ul>
/// <h2>When to Use Each Behavior</h2>
/// <h3>Browser Mode</h3>
/// Use this when you want to:
/// <ul>
///   <li>
///     Show web content to users
///   </li>
///   <li>
///     Collect analytics through your website
///   </li>
///   <li>
///     Provide a fallback experience
///   </li>
///   <li>
///     Share content that works well in browsers
///   </li>
/// </ul>
/// <h3>App Mode</h3>
/// Use this when you want to:
/// <ul>
///   <li>
///     Provide a native app experience
///   </li>
///   <li>
///     Access device-specific features
///   </li>
///   <li>
///     Show app-specific content
///   </li>
///   <li>
///     Maintain user context within your app
///   </li>
/// </ul>
typedef SWIFT_ENUM(NSInteger, CLDynamicLinkBehaviour, open) {
/// Opens the link in the device’s default web browser.
/// This is the most reliable option as it works on all devices and platforms.
/// It’s great for:
/// <ul>
///   <li>
///     General web content
///   </li>
///   <li>
///     Marketing pages
///   </li>
///   <li>
///     Content that works well in browsers
///   </li>
///   <li>
///     Fallback experience
///   </li>
///   <li>
///     Public content sharing
///   </li>
///   <li>
///     Analytics tracking
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
/// let builder = CLDynamicLinkBuilder(
///     destinationURL: "https://yourapp.com/blog",
///     domain: "yourapp.page.link"
/// )
///     .setIOSBehaviour(.browser)
///     .setAndroidBehaviour(.browser)
///
/// \endcodenote:
/// This will always open in a browser, even if your app is installed
/// important:
/// Make sure your web content is mobile-friendly
/// warning:
/// Browser mode might not provide the same features as your app
  CLDynamicLinkBehaviourBrowser = 1,
/// Attempts to open the link directly in your app.
/// This provides the best user experience when your app is installed, as it:
/// <ul>
///   <li>
///     Opens content directly in your app
///   </li>
///   <li>
///     Maintains app context
///   </li>
///   <li>
///     Provides native features
///   </li>
///   <li>
///     Creates a seamless experience
///   </li>
///   <li>
///     Uses native UI components
///   </li>
///   <li>
///     Accesses device capabilities
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
/// let builder = CLDynamicLinkBuilder(
///     destinationURL: "https://yourapp.com/profile",
///     domain: "yourapp.page.link"
/// )
///     .setIOSBehaviour(.app)
///     .setAndroidBehaviour(.app)
///
/// \endcodenote:
/// If the app isn’t installed, it will fall back to the browser
/// important:
/// Make sure your app can handle the destination URL
/// warning:
/// Test the fallback behavior when the app isn’t installed
  CLDynamicLinkBehaviourApp = 2,
};

/// A builder for creating dynamic links with various configurations.
/// This builder helps you create dynamic links with a fluent, easy-to-use interface.
/// It supports setting up everything from basic link properties to advanced tracking
/// and social sharing parameters.
/// <h2>Quick Start</h2>
/// \code
///     // Basic link creation
///     let link = CLDynamicLinkBuilder(
///         destinationURL: "https://yourapp.com/content",
///         domain: "yourapp.page.link"
///     )
///         .setIOSBehaviour(.app)
///         .setAndroidBehaviour(.browser)
///         .build()
///     
///     // Advanced link with all features
///     let advancedLink = CLDynamicLinkBuilder(
///         destinationURL: "https://yourapp.com/content",
///         domain: "yourapp.page.link"
///     )
///         .setLinkName("summer-sale")
///         .setSelectedPath("promo/summer")
///         .setSocialParameters(
///             title: "Summer Sale",
///             description: "Check out our amazing deals!",
///             imageUrl: "https://yourapp.com/images/sale.jpg"
///         )
///         .setUTMParameters(
///             source: "email",
///             medium: "newsletter",
///             campaign: "summer2024"
///         )
///         .build()
///
/// \endcode<h2>Features</h2>
/// <ul>
///   <li>
///     Basic link configuration (URL, domain, behavior)
///   </li>
///   <li>
///     Platform-specific behavior settings
///   </li>
///   <li>
///     Social sharing parameters
///   </li>
///   <li>
///     UTM tracking parameters
///   </li>
///   <li>
///     Custom path configuration
///   </li>
///   <li>
///     Link naming and organization
///   </li>
/// </ul>
/// <h2>Best Practices</h2>
/// <ul>
///   <li>
///     Always provide a valid destination URL
///   </li>
///   <li>
///     Use meaningful link names for better organization
///   </li>
///   <li>
///     Set appropriate platform behaviors
///   </li>
///   <li>
///     Include UTM parameters for tracking
///   </li>
///   <li>
///     Add social parameters for better sharing
///   </li>
///   <li>
///     Test links on both iOS and Android
///   </li>
/// </ul>
/// <h2>Technical Notes</h2>
/// <ul>
///   <li>
///     Default behavior is set to <code>.app</code> for both platforms
///   </li>
///   <li>
///     Links are validated before creation
///   </li>
/// </ul>
SWIFT_CLASS("_TtC13ChottuLinkSDK20CLDynamicLinkBuilder")
@interface CLDynamicLinkBuilder : NSObject
/// Creates a new dynamic link builder.
/// note:
/// Both parameters are required to create a valid dynamic link
/// important:
/// The destination URL must be a valid URL
/// warning:
/// The domain must be registered with ChottuLink
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     destinationURL: The URL where the link should redirect to
///   </li>
///   <li>
///     domain: Your custom domain for the dynamic link
///   </li>
/// </ul>
- (nonnull instancetype)initWithDestinationURL:(NSString * _Nonnull)destinationURL domain:(NSString * _Nonnull)domain OBJC_DESIGNATED_INITIALIZER;
/// Sets the behavior for iOS devices.
/// \param behaviour The desired behavior for iOS devices
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setIOSBehaviour:(enum CLDynamicLinkBehaviour)behaviour;
/// Sets the behavior for Android devices.
/// \param behaviour The desired behavior for Android devices
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setAndroidBehaviour:(enum CLDynamicLinkBehaviour)behaviour;
/// Sets a custom name for the link.
/// \param name The desired name for the link
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setLinkName:(NSString * _Nonnull)name;
/// Sets a custom path for the link.
/// \param path The desired path for the link
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setSelectedPath:(NSString * _Nonnull)path;
/// Sets the social sharing title.
/// \param title The title to be shown when sharing
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setSocialTitle:(NSString * _Nonnull)title;
/// Sets the social sharing description.
/// \param description The description to be shown when sharing
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setSocialDescription:(NSString * _Nonnull)description;
/// Sets the social sharing image URL.
/// \param imageUrl The URL of the image to be shown when sharing
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setSocialImageUrl:(NSString * _Nonnull)imageUrl;
/// Sets the UTM campaign parameter.
/// \param campaign The campaign identifier
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setUTMCampaign:(NSString * _Nonnull)campaign;
/// Sets the UTM content parameter.
/// \param content The content identifier
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setUTMContent:(NSString * _Nonnull)content;
/// Sets the UTM medium parameter.
/// \param medium The medium identifier
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setUTMMedium:(NSString * _Nonnull)medium;
/// Sets the UTM source parameter.
/// \param source The source identifier
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setUTMSource:(NSString * _Nonnull)source;
/// Sets the UTM term parameter.
/// \param term The term identifier
///
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setUTMTerm:(NSString * _Nonnull)term;
/// Builds the final dynamic link configuration.
/// note:
/// Call this method after setting all desired parameters
///
/// returns:
/// The configured dynamic link builder
- (CLDynamicLinkBuilder * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface CLDynamicLinkBuilder (SWIFT_EXTENSION(ChottuLinkSDK))
/// Sets all UTM parameters at once.
/// UTM parameters help track the effectiveness of your marketing campaigns.
/// They’re commonly used with analytics tools to measure campaign performance.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     source: The source identifier (e.g., “email”, “facebook”)
///   </li>
///   <li>
///     medium: The medium identifier (e.g., “newsletter”, “social”)
///   </li>
///   <li>
///     campaign: The campaign identifier (e.g., “summer2024”)
///   </li>
///   <li>
///     content: Optional content identifier for A/B testing
///   </li>
///   <li>
///     term: Optional term identifier for paid search
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
/// builder.setUTMParameters(
/// source: "email",
/// medium: "newsletter",
/// campaign: "summer2024",
/// content: "banner1",
/// term: "summer-sale"
/// )
///
/// \endcodenote:
/// All parameters are automatically trimmed
/// important:
/// Source, medium, and campaign are required for proper tracking
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setUTMParametersWithSource:(NSString * _Nonnull)source medium:(NSString * _Nonnull)medium campaign:(NSString * _Nonnull)campaign content:(NSString * _Nullable)content term:(NSString * _Nullable)term;
/// Sets all social sharing parameters at once.
/// These parameters control how your link appears when shared on social media
/// platforms. They help create engaging previews that encourage clicks.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     title: The title to be shown when sharing
///   </li>
///   <li>
///     description: The description to be shown when sharing
///   </li>
///   <li>
///     imageUrl: The URL of the image to be shown when sharing
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
/// builder.setSocialParameters(
/// title: "Summer Sale",
/// description: "Check out our amazing deals!",
/// imageUrl: "https://yourapp.com/images/sale.jpg"
/// )
///
/// \endcodenote:
/// All parameters are automatically trimmed
/// important:
/// The image URL must be publicly accessible
/// warning:
/// Some social platforms may cache previews
///
/// returns:
/// The builder instance for method chaining
- (nonnull instancetype)setSocialParametersWithTitle:(NSString * _Nonnull)title description:(NSString * _Nonnull)description imageUrl:(NSString * _Nonnull)imageUrl;
@end

/// <h2>Signup event payload for <code>ChottuLink/trackLead(_:)</code>.</h2>
SWIFT_CLASS("_TtC13ChottuLinkSDK10CLLeadMeta")
@interface CLLeadMeta : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable eventName;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable metadata;
- (nonnull instancetype)initWithEventName:(NSString * _Nullable)eventName metadata:(NSDictionary<NSString *, id> * _Nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
@class ResolvedLink;
/// The main entry point for the ChottuLink SDK, providing deep linking and dynamic link creation capabilities.
/// ChottuLink is a powerful SDK that helps you manage deep links and create dynamic links for your iOS app.
/// It handles everything from link resolution to deferred deep linking, making it easy to implement
/// sophisticated linking features in your app.
/// <h2>Key Features</h2>
/// <ul>
///   <li>
///     Deep link resolution and handling
///   </li>
///   <li>
///     Dynamic link creation
///   </li>
///   <li>
///     Deferred deep linking
///   </li>
///   <li>
///     Debug logging and monitoring
///   </li>
///   <li>
///     Automatic device tracking
///   </li>
/// </ul>
/// <h2>Topics</h2>
/// <h3>Essentials</h3>
/// <ul>
///   <li>
///     <code>initialize(config:)</code>
///   </li>
///   <li>
///     <code>handleLink(_:)</code>
///   </li>
/// </ul>
/// <h3>Dynamic Links</h3>
/// <ul>
///   <li>
///     <code>createDynamicLink(for:completion:)</code>
///   </li>
///   <li>
///     <code>resolveDynamicLink(from:)</code>
///   </li>
/// </ul>
/// <h2>Getting Started</h2>
/// <ol>
///   <li>
///     Initialize the SDK with your API key:
///   </li>
/// </ol>
/// \code
/// let config = CLConfiguration(apiKey: "your-api-key")
/// ChottuLink.initialize(config: config)
///
/// \endcode<ol>
///   <li>
///     Handle incoming links:
///   </li>
/// </ol>
/// \code
/// func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
///     ChottuLink.handleLink(url)
///     return true
/// }
///
/// \endcode<ol>
///   <li>
///     Create dynamic links:
///   </li>
/// </ol>
/// \code
/// // Using async/await (recommended)
/// Task {
///     do {
///         let builder = CLDynamicLinkBuilder(
///            destinationURL: "https://yourapp.com/content",
///            domain: "yourapp.chottu.link"
///         )
///         let shortURL = try await ChottuLink.createDynamicLink(for: builder)
///         print("Created link: \(shortURL)")
///     } catch {
///         print("Failed to create link: \(error)")
///     }
/// }
///
/// // Using completion handler (legacy)
/// let builder = CLDynamicLinkBuilder(
///       destinationURL: "https://yourapp.com/content",
///       domain: "yourapp.chottu.link"
///   )
/// ChottuLink.createDynamicLink(for: builder) { link, error in
///     if let link = link {
///         // Share the link with your users
///     }
/// }
///
/// \endcode<ol>
///   <li>
///     Get app link data:
///   </li>
/// </ol>
/// \code
/// Task {
///     do {
///         let appLinkData = try await ChottuLink.getAppLinkDataFromUrl("https://ch.link/abc123")
///         if let destinationURL = appLinkData.link {
///             // Navigate to the destination
///         }
///     } catch {
///         print("Failed to get app link data: \(error)")
///     }
/// }
///
/// \endcode<h2>Important Notes</h2>
/// <ul>
///   <li>
///     Always initialize the SDK before using any of its features
///   </li>
///   <li>
///     Keep your API key secure and never expose it in client-side code
///   </li>
///   <li>
///     Enable debug mode only during development
///   </li>
///   <li>
///     Use the async/await version of methods when possible for better error handling
///   </li>
///   <li>
///     <code>getAppLinkDataFromUrl(from:)</code> provide the same functionality as <code>resolveDynamicLink(from:)</code> but with a name consistent with the Android SDK.
///   </li>
/// </ul>
/// <hr/>
SWIFT_CLASS("_TtC13ChottuLinkSDK10ChottuLink")
@interface ChottuLink : NSObject
/// Initializes the ChottuLink SDK with your configuration.
/// This is the first method you should call when setting up the SDK. It validates your API key,
/// sets up the necessary infrastructure, and prepares the SDK for use.
/// <h2>Example</h2>
/// \code
/// let config = CLConfiguration(
///     apiKey: "your-mobile-api-key",
///     isDebugEnabled: true,
///     delegate: self
/// )
/// ChottuLink.initialize(config: config)
///
/// \endcodenote:
/// Call this method as early as possible in your app’s lifecycle, ideally in <code>application(_:didFinishLaunchingWithOptions:)</code>
/// important:
/// The API key is required and must be valid
/// <hr/>
/// \param config Your SDK configuration, including the API key and debug settings
///
+ (void)initializeWithConfig:(CLConfiguration * _Nonnull)config;
/// Handles an incoming deep link URL.
/// When your app receives a deep link (for example, through URL schemes or Universal Links),
/// pass it to this method to resolve and handle it appropriately.
/// <h2>Example</h2>
/// \code
/// // In your URL handling code
/// func handleIncomingURL(_ url: URL) {
///    ChottuLink.handleLink(url)
/// }
///
/// \endcodenote:
/// This method is asynchronous and will notify the delegate of the result
/// important:
/// Make sure the SDK is initialized before calling this method
/// <hr/>
/// \param shortURL The URL to handle (can be a short URL or a full deep link)
///
+ (void)handleLink:(NSURL * _Nonnull)shortURL;
/// Creates a dynamic link that you can share with your users.
/// Dynamic links are powerful tools for user acquisition and engagement. They can contain
/// custom parameters, track user behavior, and provide a seamless experience across platforms.
/// <ul>
///   <li>
///     <code>ChottuLinkError.notInitialized</code> if sdk is not intialized
///   </li>
///   <li>
///     <code>ChottuLinkError.invalidAPIKey</code> if the API key is not available
///   </li>
///   <li>
///     <code>ChottuLinkError.missingKeys</code> if required configuration is missing
///   </li>
///   <li>
///     <code>ChottuLinkError.duplicatePath</code> if the path already exists
///   </li>
///   <li>
///     <code>ChottuLinkError.badRequest</code> if the request is invalid
///   </li>
///   <li>
///     Network errors if the request fails
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
/// Task {
///     do {
///         let builder = CLDynamicLinkBuilder(
///             destinationURL: "https://yourapp.com/content",
///             domain: "yourapp.chottu.link"
///         )
///         
///         let shortURL = try await ChottuLink.createDynamicLink(for: builder)
///         print("Created link: \(shortURL)")
///     } catch {
///         print("Failed to create link: \(error)")
///     }
/// }
///
/// \endcodenote:
/// This method requires the SDK to be initialized before use
/// important:
/// Make sure you have a valid internet connection when creating links
/// <hr/>
/// \param link The configuration for your dynamic link
///
///
/// throws:
///
///
/// returns:
/// A <code>CreateDynamicLinkResponse</code> object containing the created link details
+ (void)createDynamicLinkFor:(CLDynamicLinkBuilder * _Nonnull)link completionHandler:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completionHandler;
/// Gets app link data from a URL.
/// This method takes a URL and retrieves the associated app link data,
/// returning a <code>ResolvedLink</code> object containing both the original and resolved URLs.
/// note:
/// This is an <code>async</code> method and should be awaited.
/// <ul>
///   <li>
///     <code>ChottuLinkError.notInitialized</code> if sdk is not intialized
///   </li>
///   <li>
///     <code>ChottuLinkError.invalidURL</code> if the URL is malformed
///   </li>
///   <li>
///     <code>ChottuLinkError.invalidAPIKey</code> if the API key is not available
///   </li>
///   <li>
///     <code>ChottuLinkError.invalidResponse</code> if the server response is invalid
///   </li>
///   <li>
///     Network errors if the request fails
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
/// do {
///     let appLinkData = try await ChottuLink.getAppLinkDataFromUrl("https://ch.link/abc123")
///     print("Resolved URL: \(appLinkData.link?.absoluteString ?? "")")
/// } catch {
///    print("Failed to get app link data: \(error)")
/// }
///
/// \endcode<hr/>
/// \param shortURL The shortened URL string to be resolved.
///
///
/// throws:
///
///
/// returns:
/// A <code>ResolvedLink</code> object containing both the original and resolved URLs.
+ (void)getAppLinkDataFromUrlFrom:(NSString * _Nonnull)shortURL completionHandler:(void (^ _Nonnull)(ResolvedLink * _Nullable, NSError * _Nullable))completionHandler;
+ (CLAttributionData * _Nullable)getAttributionData SWIFT_WARN_UNUSED_RESULT;
+ (void)identify:(CLCustomerMeta * _Nonnull)customer;
+ (void)trackLead:(CLLeadMeta * _Nullable)meta;
+ (void)trackConversion:(CLConversionMeta * _Nonnull)meta;
+ (void)trackEventWithName:(NSString * _Nonnull)name data:(NSDictionary<NSString *, id> * _Nullable)data;
+ (void)flush;
+ (void)logout;
+ (void)optOut:(BOOL)enabled;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isOptedOut;)
+ (BOOL)isOptedOut SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A delegate protocol for receiving events and handling deep link interactions from the ChottuLink SDK.
/// This protocol provides a comprehensive set of callbacks for handling various deep link scenarios,
/// including successful resolutions, errors, and lifecycle events. All delegate methods are called
/// on the main thread.
/// <h2>Overview</h2>
/// The <code>ChottuLinkDelegate</code> protocol is your window into the SDK’s world. It lets you:
/// <ul>
///   <li>
///     Track deep link resolutions
///   </li>
///   <li>
///     Handle errors gracefully
///   </li>
///   <li>
///     Monitor SDK initialization
///   </li>
///   <li>
///     Respond to lifecycle events
///   </li>
/// </ul>
/// <h2>Quick Start</h2>
/// \code
///  class MyViewController: UIViewController, ChottuLinkDelegate {
///      override func viewDidLoad() {
///          super.viewDidLoad()
///          
///          // Initialize SDK with delegate
///          let config = CLConfiguration(
///              apiKey: "your-api-key",
///              delegate: self
///          )
///          ChottuLink.initialize(config: config)
///      }
///      
///      // Handle successful deep link resolution
///      func chottuLink(didResolveDeepLink link: URL, metadata: [String: Any]?) {
///          // Navigate to the appropriate screen
///          handleDeepLink(link)
///      }
///      
///      // Handle deep link errors
///      func chottuLink(didFailToResolveDeepLink originalURL: URL?, error: Error) {
///          // Show error to user
///          showError(error)
///      }
///  }
///
/// \endcode<h2>Best Practices</h2>
/// <ul>
///   <li>
///     Implement only the delegate methods you need
///   </li>
///   <li>
///     Handle errors appropriately
///   </li>
///   <li>
///     Use metadata for additional context
///   </li>
///   <li>
///     Keep delegate methods lightweight
///   </li>
///   <li>
///     Update UI on the main thread
///   </li>
/// </ul>
/// <h2>Technical Notes</h2>
/// <ul>
///   <li>
///     All delegate methods are called on the main thread
///   </li>
///   <li>
///     All methods are optional
///   </li>
///   <li>
///     The delegate should be a class instance
///   </li>
///   <li>
///     The delegate is weakly referenced
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP13ChottuLinkSDK18ChottuLinkDelegate_")
@protocol ChottuLinkDelegate
/// Called when the SDK is successfully initialized.
/// This method is called when the SDK has been successfully initialized and
/// is ready to handle deep links. Use this to perform any necessary setup
/// or verification.
/// <ul>
///   <li>
///     API key
///   </li>
///   <li>
///     Debug mode status
///   </li>
///   <li>
///     Delegate reference
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
///      func chottuLink(didInitializeWith configuration: CLConfiguration) {
///          // Log successful initialization
///          print("SDK initialized with API key: \(configuration.apiKey)")
///          
///          // Perform any necessary setup
///          setupDeepLinkHandling()
///      }
///
/// \endcodenote:
/// This method is called on the main thread
/// important:
/// Verify the configuration is correct
/// \param configuration The configuration used to initialize the SDK,
/// including:
///
- (void)chottuLinkWithDidInitializeWith:(CLConfiguration * _Nonnull)configuration;
/// Called when SDK initialization fails.
/// This method is called when the SDK fails to initialize properly. Use this
/// to handle initialization errors and provide appropriate feedback.
/// <ul>
///   <li>
///     Invalid API key
///   </li>
///   <li>
///     Network connectivity issues
///   </li>
///   <li>
///     Server errors
///   </li>
///   <li>
///     Configuration errors
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
///      func chottuLink(didFailToInitializeWith error: Error) {
///          // Show error to user
///          let message = "Failed to initialize SDK: \(error.localizedDescription)"
///          showAlert(title: "Initialization Error", message: message)
///          
///          // Log error for analytics
///          Analytics.logError(error, context: "sdk_initialization")
///      }
///
/// \endcodenote:
/// This method is called on the main thread
/// important:
/// Handle initialization failures appropriately
/// \param error The error that occurred during initialization, which could be:
///
- (void)chottuLinkWithDidFailToInitializeWith:(NSError * _Nonnull)error;
/// Called when a deep link is successfully resolved to its final destination.
/// This method is called when the SDK successfully resolves a deep link to its
/// final destination. Use this to navigate to the appropriate screen or perform
/// the necessary action based on the link.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     link: The resolved final URL that should be handled
///   </li>
///   <li>
///     metadata: Additional metadata associated with the deep link, such as:
///   </li>
///   <li>
///     <code>isDeferred</code>: Boolean indicating if this is a deferred deep link
///   </li>
///   <li>
///     <code>resolvedAt</code>: Timestamp of when the link was resolved
///   </li>
///   <li>
///     <code>campaign</code>: Marketing campaign information
///   </li>
///   <li>
///     <code>source</code>: Source of the deep link
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
///      func chottuLink(didResolveDeepLink link: URL, metadata: [String: Any]?) {
///          // Check if it's a product link
///          if link.path.contains("/product/") {
///              let productId = link.lastPathComponent
///              navigateToProduct(id: productId)
///          }
///          
///          // Log analytics
///          if let campaign = metadata?["campaign"] as? String {
///              Analytics.trackDeepLink(campaign: campaign)
///          }
///      }
///
/// \endcodenote:
/// This method is called on the main thread
/// important:
/// Handle the link appropriately for your app’s navigation
- (void)chottuLinkWithDidResolveDeepLink:(NSURL * _Nonnull)link metadata:(NSDictionary<NSString *, id> * _Nullable)metadata;
/// Called when a deep link resolution fails.
/// This method is called when the SDK encounters an error while trying to
/// resolve a deep link. Use this to handle errors gracefully and provide
/// feedback to the user.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     originalURL: The original URL that failed to resolve, if available
///   </li>
///   <li>
///     error: The error that occurred during resolution, which could be:
///   </li>
///   <li>
///     Network errors
///   </li>
///   <li>
///     Invalid URL errors
///   </li>
///   <li>
///     Server errors
///   </li>
///   <li>
///     Timeout errors
///   </li>
/// </ul>
/// <h2>Example</h2>
/// \code
///      func chottuLink(didFailToResolveDeepLink originalURL: URL?, error: Error) {
///          // Show error to user
///          let message = "Failed to open link: \(error.localizedDescription)"
///          showAlert(title: "Error", message: message)
///          
///          // Log error for analytics
///          Analytics.logError(error, context: "deep_link_resolution")
///      }
///
/// \endcodenote:
/// This method is called on the main thread
/// important:
/// Always provide user feedback for errors
- (void)chottuLinkWithDidFailToResolveDeepLink:(NSURL * _Nullable)originalURL error:(NSError * _Nonnull)error;
@end

/// <h2>An enumeration representing possible errors that can occur in the ChottuLink SDK.</h2>
typedef SWIFT_ENUM(NSInteger, ChottuLinkError, open) {
/// Indicates that the request was malformed or invalid.
  ChottuLinkErrorBadRequest = 0,
/// Indicates that the provided path is already in use and cannot be reused.
  ChottuLinkErrorDuplicatePath = 1,
/// Indicates that the provided API key is invalid or empty.
  ChottuLinkErrorInvalidAPIKey = 2,
/// Indicates that the URL used for a request was malformed or invalid.
  ChottuLinkErrorInvalidURL = 3,
/// Indicates that the server returned an unexpected or malformed response.
  ChottuLinkErrorInvalidResponse = 4,
/// Indicates that the required keys are missing.
  ChottuLinkErrorMissingKeys = 5,
/// Indicates that the SDK was not intialized
  ChottuLinkErrorNotInitialized = 6,
/// Indicates a lower-level networking error occurred.
/// \param error The underlying system or URL session error.
///
  ChottuLinkErrorNetworkError = 7,
/// Indicates the server responded with an error HTTP status code.
/// \param statusCode The HTTP status code returned by the server.
///
  ChottuLinkErrorServerError = 8,
/// Indicates that the user was denied or restricted permission for this operation.
  ChottuLinkErrorNotAuthorized = 9,
/// Indicates the Short URL was not found
  ChottuLinkErrorShortURLNotFound = 10,
};
static NSString * _Nonnull const ChottuLinkErrorDomain = @"ChottuLinkSDK.ChottuLinkError";

SWIFT_CLASS("_TtC13ChottuLinkSDK12ResolvedLink")
@interface ResolvedLink : NSObject
@property (nonatomic, readonly) BOOL isDeferred;
@property (nonatomic, readonly, copy) NSURL * _Nullable link;
@property (nonatomic, readonly, copy) NSURL * _Nullable shortLink;
@property (nonatomic, readonly, copy) NSURL * _Nullable shortLinkRaw;
- (nonnull instancetype)initWithIsDeferred:(BOOL)isDeferred link:(NSURL * _Nullable)link shortLink:(NSURL * _Nullable)shortLink shortLinkRaw:(NSURL * _Nullable)shortLinkRaw OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
